config/routes.rb
Blorgh::Engine.routes.draw do
  resources :articles
  get 'admin', to: "articles#admin"
  root 'articles#index'
end

app/models/blorgh/application_record.rb
module Blorgh
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/blorgh/article.rb
module Blorgh
  class Article < ApplicationRecord
  end
end

app/controllers/blorgh/application_controller.rb
module Blorgh
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/blorgh/articles_controller.rb
require_dependency "blorgh/application_controller"

module Blorgh
  class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    # GET /articles
    def index
      @articles = Article.all
    end

    # GET /articles/1
    def show
    end

    # GET /articles/new
    def new
      @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles
    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to @article, notice: 'Article was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /articles/1
    def update
      if @article.update(article_params)
        redirect_to @article, notice: 'Article was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /articles/1
    def destroy
      @article.destroy
      redirect_to articles_url, notice: 'Article was successfully destroyed.'
    end

    def admin
      @articles = Article.all
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_article
        @article = Article.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def article_params
        params.require(:article).permit(:title, :text, :published)
      end
  end
end

app/helpers/blorgh/application_helper.rb
require 'redcarpet'

module Blorgh
  module ApplicationHelper
    def markdown(text)
        markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
        markdown.render(text).html_safe
    end
  end
end

app/helpers/blorgh/articles_helper.rb
module Blorgh
  module ArticlesHelper
  end
end

app/views/blorgh/articles/_article_preview.html.erb
=======================<%= article.created_at %><br>
<%= article.title %><br>
<%= markdown(truncate(article.text) { link_to "Continue", article })%><br>
=======================================<br><br>

app/views/blorgh/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>
  <br>

  <div class="field">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %><br>
    <%= form.text_area :text, size: "100x200" %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blorgh/articles/admin.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Publicado</th>
      <th>Título</th>
      <th>Texto truncado</th>
      <th>Tamaño</th>
      <th colspan="3"> Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.published %></td>
        <td><%= article.title %></td>
        <td><%= truncate(article.text)%></td>
        <td><%= article.text.size%></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/blorgh/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/blorgh/articles/index.html.erb
<p id="notice"><%= notice %></p>

<% @articles.where(:published => true).each do |article| %>
  <%= render "blorgh/articles/article_preview", article: article %>
<% end %>

<br>

app/views/blorgh/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/blorgh/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @article.title %>
</h1>

<%= markdown @article.text %>

<%= link_to 'Edit', edit_article_path(@article) %>

app/views/layouts/blorgh/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blorgh</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "blorgh/application", media: "all" %>
  <%= javascript_include_tag "blorgh/application" %>
</head>
<body>

<%= link_to root_path do %>
<%= image_tag 'typewriter.svg', size: "120x120"%>
<% end %>
<%= yield %>

</body>
</html>